name: easy_mask_example
version: 0.0.1
authors:
  - "Danilo Coppi"

description: TextInputMask ready to be used just passing a String patterned parameter.
homepage: https://github.com/danilocoppi/flutter-textfiled-mask

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.3
  easy_mask: ^1.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:
  uses-material-design: true


